version: '3.5'

services:
    backend:
        image: backend-project
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=postgres
        container_name: backend
    
    frontend:
        image: frontend-project
        ports:
            - 5000:5000
        container_name: frontend
    
    redis:
        image: redis:alpine
        container_name: redis

    db:
        image: postgres:alpine
        restart: always
        volumes:
            - ./database:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres

volumes:
    database:
