version: '3.5'

services:
    backend:
        build: ./ml-kurkkumopo-backend
        ports:
            - 5000:5000
        container_name: backend
        volumes:
            - ./model:/src/model
        depends_on:
            - training

    frontend:
        build: ./ml-kurkkumopo-frontend
        ports:
            - 3000:3000
        container_name: frontend
        depends_on:
            - backend

    training:
        build: ./ml-kurkkumopo-training
        volumes:
            - ./ml-kurkkumopo-training/imgs:/src/imgs
            - ./model:/src/model
        container_name: training

volumes:
    model:
